"""
Project Strategy Model

Stores AI-generated strategy insights for proposals:
- Win Themes
- Competitive Analysis
- Pricing Estimates
- Legal Review

Each project can have one active strategy record that persists across sessions.
"""
from datetime import datetime
from ..extensions import db


class ProjectStrategy(db.Model):
    """
    Stores strategy insights generated by AI agents for a project.
    
    Features:
    - Win themes and differentiators
    - Competitive analysis and positioning
    - Pricing estimates and breakdowns
    - Legal review and risk assessment
    """
    __tablename__ = 'project_strategies'
    
    id = db.Column(db.Integer, primary_key=True)
    project_id = db.Column(db.Integer, db.ForeignKey('projects.id'), nullable=False, unique=True)
    
    # Win Themes Data
    win_themes = db.Column(db.JSON, nullable=True)  # Full themes response
    win_themes_generated_at = db.Column(db.DateTime, nullable=True)
    
    # Competitive Analysis Data
    competitive_analysis = db.Column(db.JSON, nullable=True)  # Full analysis response
    competitive_analysis_generated_at = db.Column(db.DateTime, nullable=True)
    
    # Pricing Data
    pricing = db.Column(db.JSON, nullable=True)  # Full pricing response
    pricing_generated_at = db.Column(db.DateTime, nullable=True)
    
    # Legal Review Data
    legal_review = db.Column(db.JSON, nullable=True)  # Full legal review response
    legal_review_generated_at = db.Column(db.DateTime, nullable=True)
    
    # Metadata
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    project = db.relationship('Project', backref=db.backref('strategy', uselist=False))
    
    def to_dict(self):
        """Serialize strategy data to dictionary."""
        return {
            'id': self.id,
            'project_id': self.project_id,
            'win_themes': self.win_themes,
            'win_themes_generated_at': self.win_themes_generated_at.isoformat() if self.win_themes_generated_at else None,
            'competitive_analysis': self.competitive_analysis,
            'competitive_analysis_generated_at': self.competitive_analysis_generated_at.isoformat() if self.competitive_analysis_generated_at else None,
            'pricing': self.pricing,
            'pricing_generated_at': self.pricing_generated_at.isoformat() if self.pricing_generated_at else None,
            'legal_review': self.legal_review,
            'legal_review_generated_at': self.legal_review_generated_at.isoformat() if self.legal_review_generated_at else None,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
        }
    
    @classmethod
    def get_or_create(cls, project_id: int):
        """Get existing strategy or create new one for project."""
        strategy = cls.query.filter_by(project_id=project_id).first()
        if not strategy:
            strategy = cls(project_id=project_id)
            db.session.add(strategy)
            db.session.commit()
        return strategy
    
    def update_win_themes(self, themes_data: dict):
        """Update win themes data."""
        self.win_themes = themes_data
        self.win_themes_generated_at = datetime.utcnow()
        db.session.commit()
    
    def update_competitive_analysis(self, analysis_data: dict):
        """Update competitive analysis data."""
        self.competitive_analysis = analysis_data
        self.competitive_analysis_generated_at = datetime.utcnow()
        db.session.commit()
    
    def update_pricing(self, pricing_data: dict):
        """Update pricing data."""
        self.pricing = pricing_data
        self.pricing_generated_at = datetime.utcnow()
        db.session.commit()
    
    def update_legal_review(self, review_data: dict):
        """Update legal review data."""
        self.legal_review = review_data
        self.legal_review_generated_at = datetime.utcnow()
        db.session.commit()
