"""Add FilterDimension model

Revision ID: 0e6d47433cb0
Revises: 69b864f384be
Create Date: 2025-12-18 11:57:42.558401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6d47433cb0'
down_revision = '69b864f384be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dimension_type', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_code', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dimension_type', 'code', 'organization_id', name='uq_dimension_type_code_org')
    )
    with op.batch_alter_table('filter_dimensions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filter_dimensions_dimension_type'), ['dimension_type'], unique=False)

    with op.batch_alter_table('rfp_section_types', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rfp_section_types', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('filter_dimensions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filter_dimensions_dimension_type'))

    op.drop_table('filter_dimensions')
    # ### end Alembic commands ###
