"""Add cloud storage and embedding fields to documents

Revision ID: 1d112e34cbb7
Revises: 972bd06bdf52
Create Date: 2025-12-26 09:52:32.024638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d112e34cbb7'
down_revision = '972bd06bdf52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('file_url', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('storage_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('content_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('embedding_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('chunk_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('page_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('word_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('embedding_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('embedding_completed_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_file_id'), ['file_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_file_id'))
        batch_op.drop_column('embedding_completed_at')
        batch_op.drop_column('embedding_started_at')
        batch_op.drop_column('word_count')
        batch_op.drop_column('page_count')
        batch_op.drop_column('chunk_count')
        batch_op.drop_column('embedding_status')
        batch_op.drop_column('content_hash')
        batch_op.drop_column('content_type')
        batch_op.drop_column('storage_type')
        batch_op.drop_column('file_url')
        batch_op.drop_column('file_id')

    # ### end Alembic commands ###
