"""Add section_versions table for history tracking

Revision ID: 292145cc3e7c
Revises: 566f32932447
Create Date: 2025-12-21 16:01:00.658001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292145cc3e7c'
down_revision = '566f32932447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=True),
    sa.Column('change_summary', sa.String(length=500), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['rfp_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section_versions')
    # ### end Alembic commands ###
