"""Add trial fields

Revision ID: 52e17b074f3a
Revises: add_market_features
Create Date: 2025-12-30 12:00:58.677209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e17b074f3a'
down_revision = 'add_market_features'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_super_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_super_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
