"""Add profile_photo to users

Revision ID: 532e516e041a
Revises: 0e6d47433cb0
Create Date: 2025-12-21 06:50:00.916909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532e516e041a'
down_revision = '0e6d47433cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_photo')

    # ### end Alembic commands ###
