"""Add sections_snapshot restoration fields to proposal_versions

Revision ID: 566f32932447
Revises: f1147df8f25d
Create Date: 2025-12-21 20:40:13.935337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566f32932447'
down_revision = 'f1147df8f25d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sections_snapshot', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_restoration_point', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('restored_from_version', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal_versions', schema=None) as batch_op:
        batch_op.drop_column('restored_from_version')
        batch_op.drop_column('is_restoration_point')
        batch_op.drop_column('sections_snapshot')

    # ### end Alembic commands ###
