"""Add RFP sections models

Revision ID: 6202fc502784
Revises: 40546c242fd3
Create Date: 2025-12-16 01:17:40.140733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6202fc502784'
down_revision = '40546c242fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfp_section_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('default_prompt', sa.Text(), nullable=True),
    sa.Column('required_inputs', sa.JSON(), nullable=True),
    sa.Column('knowledge_scopes', sa.JSON(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('section_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('section_type_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['section_type_id'], ['rfp_section_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfp_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('section_type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('ai_generation_params', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['section_type_id'], ['rfp_section_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_bulk_runs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('workflow_bulk_runs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('total_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failed_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('column_mapping', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('triggered_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name='workflow_bulk_runs_triggered_by_fkey'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name='workflow_bulk_runs_workflow_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='workflow_bulk_runs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('workflows',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('workflows_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('trigger_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('trigger_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_template', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='workflows_created_by_fkey'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='workflows_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='workflows_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('workflow_runs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bulk_run_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inputs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('outputs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('step_results', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('triggered_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bulk_run_id'], ['workflow_bulk_runs.id'], name=op.f('workflow_runs_bulk_run_id_fkey')),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name=op.f('workflow_runs_triggered_by_fkey')),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('workflow_runs_workflow_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_runs_pkey'))
    )
    op.create_table('workflow_steps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('step_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('search_scope', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('workflow_steps_workflow_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_steps_pkey'))
    )
    op.drop_table('rfp_sections')
    op.drop_table('section_templates')
    op.drop_table('rfp_section_types')
    # ### end Alembic commands ###
