"""Add answer library items table

Revision ID: 7debb150e501
Revises: df381c0cfd62
Create Date: 2025-12-22 01:03:07.924918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7debb150e501'
down_revision = 'df381c0cfd62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_library_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('source_project_id', sa.Integer(), nullable=True),
    sa.Column('source_question_id', sa.Integer(), nullable=True),
    sa.Column('source_answer_id', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('times_helpful', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['source_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_library_items')
    # ### end Alembic commands ###
