"""add file_data and file_size to knowledge_items

Revision ID: 858aff81fab0
Revises: 7132082aa1a3
Create Date: 2025-12-15 12:52:45.522537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858aff81fab0'
down_revision = '7132082aa1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_items', schema=None) as batch_op:
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_data')

    # ### end Alembic commands ###
