"""Add project_strategies table

Revision ID: 972bd06bdf52
Revises: d0fb58e51c51
Create Date: 2025-12-26 02:17:38.313713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972bd06bdf52'
down_revision = 'd0fb58e51c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('win_themes', sa.JSON(), nullable=True),
    sa.Column('win_themes_generated_at', sa.DateTime(), nullable=True),
    sa.Column('competitive_analysis', sa.JSON(), nullable=True),
    sa.Column('competitive_analysis_generated_at', sa.DateTime(), nullable=True),
    sa.Column('pricing', sa.JSON(), nullable=True),
    sa.Column('pricing_generated_at', sa.DateTime(), nullable=True),
    sa.Column('legal_review', sa.JSON(), nullable=True),
    sa.Column('legal_review_generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    with op.batch_alter_table('copilot_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copilot_messages_session_id'))
        batch_op.drop_constraint(batch_op.f('copilot_messages_session_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'copilot_sessions', ['session_id'], ['id'])

    with op.batch_alter_table('copilot_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copilot_sessions_user_id'))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('loss_reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('loss_reason',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('copilot_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copilot_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('copilot_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('copilot_messages_session_id_fkey'), 'copilot_sessions', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_copilot_messages_session_id'), ['session_id'], unique=False)

    op.drop_table('project_strategies')
    # ### end Alembic commands ###
