"""Add workflow and versioning to answer library

Revision ID: bc723b471cf4
Revises: 503d186380ad
Create Date: 2025-12-24 14:52:19.593812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc723b471cf4'
down_revision = '503d186380ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_library_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('version_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('item_metadata', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('last_reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('next_review_due', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['reviewed_by'], ['id'])

    with op.batch_alter_table('feedback_learnings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_learnings_category'))
        batch_op.drop_index(batch_op.f('ix_feedback_learnings_org_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_learnings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_learnings_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_learnings_category'), ['category'], unique=False)

    with op.batch_alter_table('answer_library_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('next_review_due')
        batch_op.drop_column('last_reviewed_at')
        batch_op.drop_column('item_metadata')
        batch_op.drop_column('version_number')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
