"""Add resilience fields to agent config

Revision ID: cde26fe8ae80
Revises: add_market_features
Create Date: 2025-12-30 14:42:38.204479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde26fe8ae80'
down_revision = 'add_market_features'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add is_super_admin to users table (consolidating deleted migrations)
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_super_admin', sa.Boolean(), nullable=True))
    
    # Add resilience fields to agent_ai_configs
    with op.batch_alter_table('agent_ai_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeout_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_retries', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_ai_configs', schema=None) as batch_op:
        batch_op.drop_column('max_retries')
        batch_op.drop_column('timeout_seconds')
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_super_admin')

    # ### end Alembic commands ###
