"""Add resilience fields to agent config

Revision ID: cde26fe8ae80
Revises: f7bf836d6351
Create Date: 2025-12-30 14:42:38.204479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde26fe8ae80'
down_revision = 'f7bf836d6351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_ai_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeout_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_retries', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_ai_configs', schema=None) as batch_op:
        batch_op.drop_column('max_retries')
        batch_op.drop_column('timeout_seconds')

    # ### end Alembic commands ###
