"""Add Go/No-Go analysis fields to Project

Revision ID: d1bb3e6a74b3
Revises: 7debb150e501
Create Date: 2025-12-22 08:33:26.798007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1bb3e6a74b3'
down_revision = '7debb150e501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('go_no_go_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('go_no_go_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('go_no_go_analysis', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('go_no_go_completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('go_no_go_completed_at')
        batch_op.drop_column('go_no_go_analysis')
        batch_op.drop_column('go_no_go_score')
        batch_op.drop_column('go_no_go_status')

    # ### end Alembic commands ###
