"""add_global_folders_and_project_linking

Revision ID: d60ebc29806f
Revises: 1d112e34cbb7
Create Date: 2025-12-26 12:06:29.158302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60ebc29806f'
down_revision = '1d112e34cbb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_knowledge_folders',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=True),
    sa.Column('linked_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['knowledge_folders.id'], ),
    sa.ForeignKeyConstraint(['linked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'folder_id')
    )
    with op.batch_alter_table('knowledge_folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_global', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_folders', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('is_global')

    op.drop_table('project_knowledge_folders')
    # ### end Alembic commands ###
