"""Add workflow fields to RFP sections

Revision ID: df381c0cfd62
Revises: d68a4c07909e
Create Date: 2025-12-21 18:02:33.669545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df381c0cfd62'
down_revision = 'd68a4c07909e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rfp_sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('comments', sa.JSON(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['assigned_to'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rfp_sections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('comments')
        batch_op.drop_column('priority')
        batch_op.drop_column('due_date')
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###
