"""Add knowledge profiles and multi-dimensional filtering

Revision ID: f722678701f3
Revises: 6202fc502784
Create Date: 2025-12-16 12:36:10.712881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f722678701f3'
down_revision = '6202fc502784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geographies', sa.JSON(), nullable=True),
    sa.Column('client_types', sa.JSON(), nullable=True),
    sa.Column('currencies', sa.JSON(), nullable=True),
    sa.Column('industries', sa.JSON(), nullable=True),
    sa.Column('compliance_frameworks', sa.JSON(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('custom_tags', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_knowledge_profiles',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_profile_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_profile_id'], ['knowledge_profiles.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'knowledge_profile_id')
    )
    op.drop_table('workflow_runs')
    op.drop_table('workflow_steps')
    op.drop_table('workflow_bulk_runs')
    op.drop_table('workflows')
    with op.batch_alter_table('knowledge_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geography', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('client_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('knowledge_profile_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'knowledge_profiles', ['knowledge_profile_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('geography', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('compliance_requirements', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('client_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('project_value', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('project_value')
        batch_op.drop_column('client_name')
        batch_op.drop_column('language')
        batch_op.drop_column('compliance_requirements')
        batch_op.drop_column('industry')
        batch_op.drop_column('currency')
        batch_op.drop_column('geography')
        batch_op.drop_column('client_type')

    with op.batch_alter_table('knowledge_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('knowledge_profile_id')
        batch_op.drop_column('language')
        batch_op.drop_column('industry')
        batch_op.drop_column('currency')
        batch_op.drop_column('client_type')
        batch_op.drop_column('geography')

    op.create_table('workflows',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('workflows_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('trigger_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('trigger_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_template', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='workflows_created_by_fkey'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='workflows_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='workflows_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('workflow_bulk_runs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('workflow_bulk_runs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('total_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failed_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('column_mapping', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('triggered_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name='workflow_bulk_runs_triggered_by_fkey'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name='workflow_bulk_runs_workflow_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='workflow_bulk_runs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('workflow_steps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('step_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('search_scope', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('workflow_steps_workflow_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_steps_pkey'))
    )
    op.create_table('workflow_runs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bulk_run_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inputs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('outputs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('step_results', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('triggered_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bulk_run_id'], ['workflow_bulk_runs.id'], name=op.f('workflow_runs_bulk_run_id_fkey')),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name=op.f('workflow_runs_triggered_by_fkey')),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('workflow_runs_workflow_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_runs_pkey'))
    )
    op.drop_table('project_knowledge_profiles')
    op.drop_table('knowledge_profiles')
    # ### end Alembic commands ###
